sonar.projectKey=weslainesantana_prova03-playwright-weslainesantana
sonar.organization=weslainesantana
sonar.projectName=Playwright E2E
sonar.projectVersion=1.0
sonar.sources=./src
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/lcov.info